### ISSUE TITLE
User option

### ISSUE THREAD

**Issue by mbw290** [dbeybia/RedditImageDownloader#1]
I think having to enter the subreddit in the code directly isn't the best.  I'm going to write something that allows people to specify the url from a prompt.

**Comment by dbeybia** [comment]
Already did that, along with implementing some suggestion from https://www.reddit.com/r/Python/comments/3czr56/redditimagedownloader_download_images_from_your/
I'll push the new code right away.

**Comment by mbw290** [comment]
Cool
